# Generated by Django 2.2.1 on 2020-11-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=2000)),
                ('menu_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=4000, null=True)),
                ('text', models.TextField()),
                ('lastsaved_date', models.DateField()),
                ('release_date', models.DateField(null=True)),
                ('expire_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Active'), ('2', 'Inactive')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NewsCategory')),
            ],
        ),
    ]
